### ISSUE TITLE
How to add a datachannel in this design?

### ISSUE THREAD

**Issue by Isilwing** [shanet/WebRTC-Example#37]
I have been trying to make a datachannel work without success, Can someone point me in the right direction?

**Comment by shanet** [comment]
Hi @Isilwing, I'm catching up on issues in this repo. I hadn't really done much work with datachannels when I wrote this so I'm not sure to be honest. Being that this is intended to be a simple demo of webrtc video calling I'd say that a datachannel is outside the scope of this example though so I'm going to close this since it's not an issue with the example at hand.
