### ISSUE TITLE
Self signed certificate for IP address not working

### ISSUE THREAD

**Issue by emi-emi671** [shanet/WebRTC-Example#45]
I am trying to run this webrtc with IP address and using self signed certificate which I generated by following the steps from this post: https://medium.com/@antelle/how-to-generate-a-self-signed-ssl-certificate-for-an-ip-address-f0dd8dddf754

I am still getting Not Secure connection after replacing key and cert files in the root folder and running the node server back. Any idea?

**Comment by shanet** [comment]
A self-signed cert would need to be made trusted by your OS or browser. For development purposes it should be sufficient to use an untrusted certifcate, but if you must have a trusted one I've used https://github.com/FiloSottile/mkcert in the past. If you're hosting a WebRTC page on the public internet it would be easiest, and far more secure, to buy a domain and use Let's Encrypt to get a proper cert.

Since this isn't an issue with this repo though I'm going to close this issue.
